# Setup
title: Amin Laanaya · Journal
url: https://journal.laanaya.org
description: "This is the personal trading journal of Amin Laanaya. You can contact him via amin@laanaya.org or Discord with Bobcycle#0021."
paginate: 1
baseurl: ""
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Amin Laanaya
  url: 'https://laanaya.org'
  email: amin@laanaya.org
version: 3.0.0
nav:
  - title: Older
    url: https://journal.laanaya.org/archive
  - title: P&L
    url: https://docs.google.com/spreadsheets/d/1NtzdYQQHBkAMlRv4YanNGk7Cb_AH9ktPyNom4WiNX80/edit?usp=sharing
  - title: Home
    url: https://laanaya.org/
